`default_nettype none
module apb_regs_if #(
    parameter GROUP_COUNT = 4
) (
    input wire apb_clk,
    input wire apb_rst,
    input wire mac_clk,
    input wire mac_rst,
    input wire psel,
    input wire penable,
    input wire pwrite,
    input wire [15:0] paddr,
    input wire [31:0] pwdata,
    output wire [31:0] prdata,
    output wire pready,
    output wire pslverr,
    input wire rx_invalid_event,
    input wire rx_crc_event,
    input wire rx_oversize_event,
    input wire rx_unsupported_control_event,
    input wire pause_active,
    input wire pause_expired,
    input wire tx_error_event,
    output wire cfg_update,
    output wire [31:0] cfg_control,
    output wire [47:0] cfg_mac_addr,
    output wire [15:0] cfg_max_client_data,
    output wire cfg_pause_tx_enable,
    output wire cfg_pause_tx_soft_req,
    output wire [15:0] cfg_pause_quanta,
    output wire [15:0] cfg_max_frame_size,
    output wire [15:0] cfg_min_frame_size,
    output wire [2:0] cfg_mac_speed,
    output wire cfg_speed_override,
    input wire [2:0] effective_mac_speed,
    output wire [GROUP_COUNT*48-1:0] cfg_group_addr,
    output wire [GROUP_COUNT-1:0] cfg_group_valid,
    output wire status_request,
    output wire status_ack,
    output wire [383:0] status_snapshot
);
  apb_regs #(
      .GROUP_COUNT(GROUP_COUNT)
  ) core_inst (
      .apb_clk(apb_clk),
      .apb_rst(apb_rst),
      .mac_clk(mac_clk),
      .mac_rst(mac_rst),
      .psel(psel),
      .penable(penable),
      .pwrite(pwrite),
      .paddr(paddr),
      .pwdata(pwdata),
      .prdata(prdata),
      .pready(pready),
      .pslverr(pslverr),
      .rx_invalid_event(rx_invalid_event),
      .rx_crc_event(rx_crc_event),
      .rx_oversize_event(rx_oversize_event),
      .rx_unsupported_control_event(rx_unsupported_control_event),
      .pause_active(pause_active),
      .pause_expired(pause_expired),
      .tx_error_event(tx_error_event),
      .cfg_update(cfg_update),
      .cfg_control(cfg_control),
      .cfg_mac_addr(cfg_mac_addr),
      .cfg_max_client_data(cfg_max_client_data),
      .cfg_max_frame_size(cfg_max_frame_size),
      .cfg_min_frame_size(cfg_min_frame_size),
      .cfg_group_addr(cfg_group_addr),
      .cfg_group_valid(cfg_group_valid),
      .cfg_mac_speed(cfg_mac_speed),
      .cfg_speed_override(cfg_speed_override),
      .effective_mac_speed(effective_mac_speed),
      .cfg_pause_tx_enable(cfg_pause_tx_enable),
      .cfg_pause_tx_soft_req(cfg_pause_tx_soft_req),
      .cfg_pause_quanta(cfg_pause_quanta),
      .status_request(status_request),
      .status_ack(status_ack),
      .status_snapshot(status_snapshot)
  );
endmodule
`default_nettype wire
